name: IBG WEB CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Vue to github pages branch
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'international-board-gamers'
        reponame: 'ibg-web'
        token: ${{ secrets.GITHUB_TOKEN }}
